using System.Linq;
using System.Text;
using Forge.Generators.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Forge.Sync.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class PlanTemplateGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Forge.Sync.GeneratePlanTemplateAttribute";

    private static readonly DiagnosticDescriptor InvalidTemplate = new(
        "FORGETEMPLATE001",
        "Invalid plan template",
        "Plan template '{0}' must be a non-generic top-level partial class with valid context, operation and key types",
        "Forge.Sync",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (_, _) => true,
            static (generatorContext, _) => CreateTarget(generatorContext));
        context.RegisterSourceOutput(targets, static (productionContext, target) => Emit(productionContext, target));
    }

    private static TemplateTarget CreateTarget(GeneratorAttributeSyntaxContext context)
    {
        var attribute = context.Attributes[0];
        return new TemplateTarget(
            (INamedTypeSymbol)context.TargetSymbol,
            attribute.ConstructorArguments[0].Value as ITypeSymbol,
            attribute.ConstructorArguments[1].Value as ITypeSymbol,
            attribute.ConstructorArguments[2].Value as ITypeSymbol);
    }

    private static void Emit(SourceProductionContext context, TemplateTarget target)
    {
        if (target.ContextType is null
            || target.OperationType is null
            || target.KeyType is null
            || target.Template.Arity != 0
            || target.Template.ContainingType is not null
            || target.Template.IsRecord
            || !IsPartial(target.Template))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                InvalidTemplate,
                target.Template.Locations.FirstOrDefault(),
                target.Template.ToDisplayString()));
            return;
        }

        var source = Generate(target);
        context.AddSource(
            SymbolFormatting.HintName(target.Template, ".PlanTemplate.g.cs"),
            Microsoft.CodeAnalysis.Text.SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(TemplateTarget target)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        var ns = SymbolFormatting.Namespace(target.Template);
        if (!string.IsNullOrWhiteSpace(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";").AppendLine();
        }

        var accessibility = target.Template.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
        var templateName = SymbolFormatting.EscapeIdentifier(target.Template.Name);
        var contextName = SymbolFormatting.TypeName(target.ContextType!);
        var operationName = SymbolFormatting.TypeName(target.OperationType!);
        var keyName = SymbolFormatting.TypeName(target.KeyType!);
        builder.Append(accessibility);
        if (target.Template.IsStatic)
        {
            builder.Append(" static");
        }

        builder.Append(" partial class ").Append(templateName).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public static global::Forge.Sync.PlanTemplateInstance<").Append(operationName).Append(", ")
            .Append(keyName).Append("> Instantiate(").Append(contextName).AppendLine(" context)");
        builder.AppendLine("    {");
        builder.Append("        var builder = new global::Forge.Sync.PlanTemplateBuilder<").Append(operationName).Append(", ")
            .Append(keyName).AppendLine(">();");
        builder.AppendLine("        Build(context, builder);");
        builder.AppendLine("        return builder.Build();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    private static partial void Build(").Append(contextName).Append(" context, ")
            .Append("global::Forge.Sync.PlanTemplateBuilder<").Append(operationName).Append(", ").Append(keyName)
            .AppendLine("> builder);");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool IsPartial(INamedTypeSymbol symbol)
        => symbol.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(type => type.Modifiers.Any(static modifier => modifier.Text == "partial"));

    private sealed record TemplateTarget(
        INamedTypeSymbol Template,
        ITypeSymbol? ContextType,
        ITypeSymbol? OperationType,
        ITypeSymbol? KeyType);
}
