using System.Collections.Generic;
using System.Linq;
using System.Text;
using Forge.Generators.Shared;
using Microsoft.CodeAnalysis;

namespace Forge.Sync.Generators;

internal static class SyncEmitter
{
    public static string Emit(
        INamedTypeSymbol type,
        IReadOnlyList<IPropertySymbol> keyProperties,
        IReadOnlyList<INamedTypeSymbol?> keyComparerTypes,
        IReadOnlyList<NestedSyncProperty> nestedProperties)
    {
        var typeName = SymbolFormatting.TypeName(type);
        var syncName = type.Name + "Sync";
        var deltaName = type.Name + "Delta";
        var namespaceName = SymbolFormatting.Namespace(type);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        var accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
        builder.AppendLine("/// <summary>");
        builder.Append("/// Generated desired-state reconciler for <see cref=\"")
            .Append(typeName)
            .AppendLine("\"/>.");
        builder.AppendLine("/// </summary>");
        builder.Append(accessibility).Append(" static class ").Append(syncName).AppendLine();
        builder.AppendLine("{");

        EmitKey(builder, keyProperties, keyComparerTypes);
        builder.AppendLine();
        EmitAreEquivalent(builder, typeName, deltaName, type.IsReferenceType, nestedProperties);
        builder.AppendLine();
        EmitPlan(builder, typeName, deltaName, type.IsReferenceType, nestedProperties);
        if (nestedProperties.Count != 0)
        {
            builder.AppendLine();
            EmitNestedPlans(builder, typeName, deltaName, type.IsReferenceType, nestedProperties);
        }
        builder.AppendLine();
        EmitModeValidator(builder);
        builder.AppendLine();
        EmitIndex(builder, typeName, type.IsReferenceType);
        builder.AppendLine();
        EmitGetKey(builder, typeName, keyProperties, type.IsReferenceType);

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitKey(
        StringBuilder builder,
        IReadOnlyList<IPropertySymbol> keyProperties,
        IReadOnlyList<INamedTypeSymbol?> comparerTypes)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Strongly typed logical identity used by the generated synchronizer.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    [global::System.Diagnostics.DebuggerDisplay(\"{ToString(),nq}\")]");
        builder.AppendLine("    public readonly struct Key : global::System.IEquatable<Key>");
        builder.AppendLine("    {");

        for (var index = 0; index < keyProperties.Count; index++)
        {
            var comparerType = comparerTypes[index];
            if (comparerType is null)
            {
                continue;
            }

            builder.Append("        private static readonly global::System.Collections.Generic.IEqualityComparer<")
                .Append(SymbolFormatting.TypeName(keyProperties[index].Type))
                .Append("> s_key")
                .Append(index)
                .Append("Comparer = new ")
                .Append(SymbolFormatting.TypeName(comparerType))
                .AppendLine("();");
        }

        if (comparerTypes.Any(static comparerType => comparerType is not null))
        {
            builder.AppendLine();
        }

        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Creates a logical key.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        public Key(");
        for (var index = 0; index < keyProperties.Count; index++)
        {
            var property = keyProperties[index];
            builder.Append("            ")
                .Append(SymbolFormatting.TypeName(property.Type))
                .Append(' ')
                .Append(ParameterName(property.Name))
                .AppendLine(index == keyProperties.Count - 1 ? ")" : ",");
        }

        builder.AppendLine("        {");
        foreach (var property in keyProperties)
        {
            builder.Append("            ")
                .Append(SymbolFormatting.EscapeIdentifier(property.Name))
                .Append(" = ")
                .Append(ParameterName(property.Name))
                .AppendLine(";");
        }

        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (var property in keyProperties)
        {
            builder.AppendLine("        /// <summary>");
            builder.Append("        /// Gets the ").Append(EscapeXml(property.Name)).AppendLine(" component.");
            builder.AppendLine("        /// </summary>");
            builder.Append("        public ")
                .Append(SymbolFormatting.TypeName(property.Type))
                .Append(' ')
                .Append(SymbolFormatting.EscapeIdentifier(property.Name))
                .AppendLine(" { get; }");
            builder.AppendLine();
        }

        builder.AppendLine("        /// <inheritdoc />");
        builder.AppendLine("        public bool Equals(Key other)");
        builder.AppendLine("        {");
        builder.Append("            return ");
        for (var index = 0; index < keyProperties.Count; index++)
        {
            var property = keyProperties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Name);
            if (comparerTypes[index] is null)
            {
                builder.Append("global::System.Collections.Generic.EqualityComparer<")
                    .Append(SymbolFormatting.TypeName(property.Type))
                    .Append(">.Default.Equals(")
                    .Append(propertyName)
                    .Append(", other.")
                    .Append(propertyName)
                    .Append(')');
            }
            else
            {
                builder.Append("s_key")
                    .Append(index)
                    .Append("Comparer.Equals(")
                    .Append(propertyName)
                    .Append(", other.")
                    .Append(propertyName)
                    .Append(')');
            }

            builder.AppendLine(index == keyProperties.Count - 1 ? ";" : string.Empty);
            if (index != keyProperties.Count - 1)
            {
                builder.Append("                && ");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc />");
        builder.AppendLine("        public override bool Equals(object? obj)");
        builder.AppendLine("        {");
        builder.AppendLine("            return obj is Key other && Equals(other);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc />");
        builder.AppendLine("        public override int GetHashCode()");
        builder.AppendLine("        {");
        builder.AppendLine("            var hashCode = new global::System.HashCode();");

        for (var index = 0; index < keyProperties.Count; index++)
        {
            var property = keyProperties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Name);
            builder.Append("            hashCode.Add(")
                .Append(propertyName)
                .Append(", ");
            if (comparerTypes[index] is null)
            {
                builder.Append("global::System.Collections.Generic.EqualityComparer<")
                    .Append(SymbolFormatting.TypeName(property.Type))
                    .AppendLine(">.Default);");
            }
            else
            {
                builder.Append("s_key")
                    .Append(index)
                    .AppendLine("Comparer);");
            }
        }

        builder.AppendLine("            return hashCode.ToHashCode();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc />");
        builder.AppendLine("        public override string ToString()");
        builder.AppendLine("        {");
        builder.AppendLine("            return global::System.String.Join(");
        builder.AppendLine("                \", \",");
        for (var index = 0; index < keyProperties.Count; index++)
        {
            var property = keyProperties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Name);
            builder.Append("                \"")
                .Append(EscapeString(property.Name))
                .Append("=\" + global::System.Convert.ToString(")
                .Append(propertyName)
                .Append(", global::System.Globalization.CultureInfo.InvariantCulture)")
                .AppendLine(index == keyProperties.Count - 1 ? ");" : ",");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Compares two generated keys.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        public static bool operator ==(Key left, Key right) => left.Equals(right);");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Compares two generated keys.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        public static bool operator !=(Key left, Key right) => !left.Equals(right);");
        builder.AppendLine("    }");
    }

    private static void EmitAreEquivalent(
        StringBuilder builder,
        string typeName,
        string deltaName,
        bool isReferenceType,
        IReadOnlyList<NestedSyncProperty> nestedProperties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Determines whether complete current and desired collections require no reconciliation changes.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static bool AreEquivalent(");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<").Append(typeName).AppendLine("> current,");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<").Append(typeName).AppendLine("> desired)");
        builder.AppendLine("    {");
        builder.AppendLine("        return AreEquivalent(current, desired, global::Forge.Sync.SyncMode.Replace);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Determines whether the supplied collections require no changes under the selected reconciliation mode.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static bool AreEquivalent(");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<").Append(typeName).AppendLine("> current,");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<").Append(typeName).AppendLine("> desired,");
        builder.AppendLine("        global::Forge.Sync.SyncMode mode)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(current);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(desired);");
        builder.AppendLine("        ValidateMode(mode);");
        builder.AppendLine();
        builder.AppendLine("        var equivalent = mode != global::Forge.Sync.SyncMode.Replace || current.Count == desired.Count;");
        builder.AppendLine("        var currentByKey = Index(current, nameof(current));");
        builder.AppendLine("        var desiredKeys = new global::System.Collections.Generic.HashSet<Key>(desired.Count);");
        builder.AppendLine("        for (var index = 0; index < desired.Count; index++)");
        builder.AppendLine("        {");
        builder.AppendLine("            var desiredItem = desired[index];");
        if (isReferenceType)
        {
            builder.AppendLine("            if (desiredItem is null)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new global::System.ArgumentException(\"Sync collections cannot contain null items.\", nameof(desired));");
            builder.AppendLine("            }");
            builder.AppendLine();
        }

        builder.AppendLine("            var key = GetKey(desiredItem);");
        builder.AppendLine("            if (!desiredKeys.Add(key))");
        builder.AppendLine("            {");
        builder.Append("                throw new global::Forge.Sync.DuplicateSyncKeyException(typeof(")
            .Append(typeName).AppendLine("), nameof(desired), key.ToString());");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!currentByKey.TryGetValue(key, out var currentItem))");
        builder.AppendLine("            {");
        builder.AppendLine("                equivalent = false;");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.Append("            if (!").Append(deltaName).AppendLine(".AreEquivalent(currentItem, desiredItem))");
        builder.AppendLine("            {");
        builder.AppendLine("                equivalent = false;");
        builder.AppendLine("            }");

        foreach (var nested in nestedProperties)
        {
            var propertyName = SymbolFormatting.EscapeIdentifier(nested.Property.Name);
            var childSyncType = GeneratedTypeName(nested.ItemType, "Sync");
            builder.Append("            if (!").Append(childSyncType).Append(".AreEquivalent(currentItem.")
                .Append(propertyName).Append(", desiredItem.").Append(propertyName).Append(", ")
                .Append(SyncModeExpression(nested.Mode)).AppendLine("))");
            builder.AppendLine("            {");
            builder.AppendLine("                equivalent = false;");
            builder.AppendLine("            }");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return equivalent;");
        builder.AppendLine("    }");
    }

    private static void EmitPlan(
        StringBuilder builder,
        string typeName,
        string deltaName,
        bool isReferenceType,
        IReadOnlyList<NestedSyncProperty> nestedProperties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Reconciles complete current and desired state without performing any I/O.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static global::Forge.Sync.SyncPlan<")
            .Append(typeName).Append(", Key, ").Append(deltaName).AppendLine("> Plan(");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<")
            .Append(typeName).AppendLine("> current,");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<")
            .Append(typeName).AppendLine("> desired)");
        builder.AppendLine("    {");
        builder.AppendLine("        return Plan(current, desired, global::Forge.Sync.SyncMode.Replace);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Reconciles current state with complete or partial desired state without performing any I/O.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static global::Forge.Sync.SyncPlan<")
            .Append(typeName).Append(", Key, ").Append(deltaName).AppendLine("> Plan(");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<")
            .Append(typeName).AppendLine("> current,");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<")
            .Append(typeName).AppendLine("> desired,");
        builder.AppendLine("        global::Forge.Sync.SyncMode mode)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(current);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(desired);");
        builder.AppendLine("        ValidateMode(mode);");
        builder.AppendLine();
        builder.AppendLine("        var currentByKey = Index(current, nameof(current));");
        builder.AppendLine("        var desiredKeys = new global::System.Collections.Generic.HashSet<Key>(desired.Count);");
        builder.Append("        var added = new global::System.Collections.Generic.List<global::Forge.Sync.SyncAddition<")
            .Append(typeName).AppendLine(", Key>>();");
        builder.Append("        var removed = new global::System.Collections.Generic.List<global::Forge.Sync.SyncRemoval<")
            .Append(typeName).AppendLine(", Key>>();");
        builder.Append("        var updated = new global::System.Collections.Generic.List<global::Forge.Sync.SyncUpdate<")
            .Append(typeName).Append(", Key, ").Append(deltaName).AppendLine(">>();");
        builder.Append("        var unchanged = new global::System.Collections.Generic.List<global::Forge.Sync.SyncUnchanged<")
            .Append(typeName).AppendLine(", Key>>();");
        builder.Append("        var preserved = new global::System.Collections.Generic.List<global::Forge.Sync.SyncPreserved<")
            .Append(typeName).AppendLine(", Key>>();");
        builder.AppendLine();
        builder.AppendLine("        for (var index = 0; index < desired.Count; index++)");
        builder.AppendLine("        {");
        builder.AppendLine("            var desiredItem = desired[index];");
        if (isReferenceType)
        {
            builder.AppendLine("            if (desiredItem is null)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new global::System.ArgumentException(\"Sync collections cannot contain null items.\", nameof(desired));");
            builder.AppendLine("            }");
            builder.AppendLine();
        }

        builder.AppendLine("            var key = GetKey(desiredItem);");
        builder.AppendLine("            if (!desiredKeys.Add(key))");
        builder.AppendLine("            {");
        builder.Append("                throw new global::Forge.Sync.DuplicateSyncKeyException(typeof(")
            .Append(typeName).AppendLine("), nameof(desired), key.ToString());");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!currentByKey.TryGetValue(key, out var currentItem))");
        builder.AppendLine("            {");
        builder.Append("                added.Add(new global::Forge.Sync.SyncAddition<")
            .Append(typeName).AppendLine(", Key>(key, desiredItem));");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.Append("            var hasChanges = !").Append(deltaName).AppendLine(".AreEquivalent(currentItem, desiredItem);");
        foreach (var nested in nestedProperties)
        {
            var propertyName = SymbolFormatting.EscapeIdentifier(nested.Property.Name);
            var childSyncType = GeneratedTypeName(nested.ItemType, "Sync");
            builder.Append("            hasChanges |= !").Append(childSyncType).Append(".AreEquivalent(currentItem.")
                .Append(propertyName).Append(", desiredItem.").Append(propertyName).Append(", ")
                .Append(SyncModeExpression(nested.Mode)).AppendLine(");");
        }

        builder.AppendLine("            if (!hasChanges)");
        builder.AppendLine("            {");
        builder.Append("                unchanged.Add(new global::Forge.Sync.SyncUnchanged<")
            .Append(typeName).AppendLine(", Key>(key, currentItem, desiredItem));");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.Append("            var delta = ").Append(deltaName).AppendLine(".Between(currentItem, desiredItem);");
        builder.Append("            updated.Add(new global::Forge.Sync.SyncUpdate<")
            .Append(typeName).Append(", Key, ").Append(deltaName)
            .AppendLine(">(key, currentItem, desiredItem, delta));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        for (var index = 0; index < current.Count; index++)");
        builder.AppendLine("        {");
        builder.AppendLine("            var currentItem = current[index];");
        builder.AppendLine("            var key = GetKey(currentItem);");
        builder.AppendLine("            if (desiredKeys.Contains(key))");
        builder.AppendLine("            {");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (mode == global::Forge.Sync.SyncMode.Upsert)");
        builder.AppendLine("            {");
        builder.Append("                preserved.Add(new global::Forge.Sync.SyncPreserved<")
            .Append(typeName).AppendLine(", Key>(key, currentItem));");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.Append("                removed.Add(new global::Forge.Sync.SyncRemoval<")
            .Append(typeName).AppendLine(", Key>(key, currentItem));");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append("        return new global::Forge.Sync.SyncPlan<")
            .Append(typeName).Append(", Key, ").Append(deltaName)
            .AppendLine(">(added, removed, updated, unchanged, preserved);");
        builder.AppendLine("    }");
    }

    private static void EmitNestedPlans(
        StringBuilder builder,
        string typeName,
        string deltaName,
        bool isReferenceType,
        IReadOnlyList<NestedSyncProperty> nestedProperties)
    {
        for (var index = 0; index < nestedProperties.Count; index++)
        {
            var nested = nestedProperties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(nested.Property.Name);
            var methodName = "Plan" + nested.Property.Name;
            var childTypeName = SymbolFormatting.TypeName(nested.ItemType);
            var childSyncType = GeneratedTypeName(nested.ItemType, "Sync");
            var childDeltaType = GeneratedTypeName(nested.ItemType, "Delta");

            builder.AppendLine("    /// <summary>");
            builder.Append("    /// Reconciles nested collection ").Append(nested.Property.Name).AppendLine(".");
            builder.AppendLine("    /// </summary>");
            builder.Append("    public static global::Forge.Sync.SyncPlan<")
                .Append(childTypeName).Append(", ").Append(childSyncType).Append(".Key, ")
                .Append(childDeltaType).Append("> ").Append(methodName).AppendLine("(");
            builder.Append("        ").Append(typeName).AppendLine(" current,");
            builder.Append("        ").Append(typeName).AppendLine(" desired)");
            builder.AppendLine("    {");
            if (isReferenceType)
            {
                builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(current);");
                builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(desired);");
            }

            builder.Append("        return ").Append(childSyncType).Append(".Plan(current.")
                .Append(propertyName).Append(", desired.").Append(propertyName).Append(", ")
                .Append(SyncModeExpression(nested.Mode)).AppendLine(");");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.Append("    /// Reconciles nested collection ").Append(nested.Property.Name)
                .AppendLine(" for an existing parent update.");
            builder.AppendLine("    /// </summary>");
            builder.Append("    public static global::Forge.Sync.SyncPlan<")
                .Append(childTypeName).Append(", ").Append(childSyncType).Append(".Key, ")
                .Append(childDeltaType).Append("> ").Append(methodName).AppendLine("(");
            builder.Append("        global::Forge.Sync.SyncUpdate<").Append(typeName).Append(", Key, ")
                .Append(deltaName).AppendLine("> update)");
            builder.AppendLine("    {");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(update);");
            builder.Append("        return ").Append(methodName).AppendLine("(update.Current, update.Desired);");
            builder.AppendLine("    }");

            if (index != nestedProperties.Count - 1)
            {
                builder.AppendLine();
            }
        }
    }

    private static string GeneratedTypeName(INamedTypeSymbol type, string suffix)
    {
        var namespaceName = SymbolFormatting.Namespace(type);
        return string.IsNullOrEmpty(namespaceName)
            ? "global::" + type.Name + suffix
            : "global::" + namespaceName + "." + type.Name + suffix;
    }

    private static string SyncModeExpression(int mode)
    {
        return mode == 1
            ? "global::Forge.Sync.SyncMode.Upsert"
            : "global::Forge.Sync.SyncMode.Replace";
    }

    private static void EmitModeValidator(StringBuilder builder)
    {
        builder.AppendLine("    private static void ValidateMode(global::Forge.Sync.SyncMode mode)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (mode != global::Forge.Sync.SyncMode.Replace && mode != global::Forge.Sync.SyncMode.Upsert)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentOutOfRangeException(nameof(mode), mode, null);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void EmitIndex(StringBuilder builder, string typeName, bool isReferenceType)
    {
        builder.Append("    private static global::System.Collections.Generic.Dictionary<Key, ")
            .Append(typeName).AppendLine("> Index(");
        builder.Append("        global::System.Collections.Generic.IReadOnlyList<")
            .Append(typeName).AppendLine("> items,");
        builder.AppendLine("        string collectionName)");
        builder.AppendLine("    {");
        builder.Append("        var result = new global::System.Collections.Generic.Dictionary<Key, ")
            .Append(typeName).AppendLine(">(items.Count);");
        builder.AppendLine();
        builder.AppendLine("        for (var index = 0; index < items.Count; index++)");
        builder.AppendLine("        {");
        builder.AppendLine("            var item = items[index];");
        if (isReferenceType)
        {
            builder.AppendLine("            if (item is null)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new global::System.ArgumentException(\"Sync collections cannot contain null items.\", collectionName);");
            builder.AppendLine("            }");
            builder.AppendLine();
        }

        builder.AppendLine("            var key = GetKey(item);");
        builder.AppendLine("            if (!result.TryAdd(key, item))");
        builder.AppendLine("            {");
        builder.Append("                throw new global::Forge.Sync.DuplicateSyncKeyException(typeof(")
            .Append(typeName).AppendLine("), collectionName, key.ToString());");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return result;");
        builder.AppendLine("    }");
    }

    private static void EmitGetKey(
        StringBuilder builder,
        string typeName,
        IReadOnlyList<IPropertySymbol> keyProperties,
        bool isReferenceType)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets the logical key for an item using the generated key semantics.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static Key GetKey(").Append(typeName).AppendLine(" item)");
        builder.AppendLine("    {");
        if (isReferenceType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(item);");
        }

        builder.AppendLine("        return new Key(");

        for (var index = 0; index < keyProperties.Count; index++)
        {
            var propertyName = SymbolFormatting.EscapeIdentifier(keyProperties[index].Name);
            builder.Append("            item.").Append(propertyName)
                .AppendLine(index == keyProperties.Count - 1 ? ");" : ",");
        }

        builder.AppendLine("    }");
    }

    private static string ParameterName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName))
        {
            return "value";
        }

        var first = char.ToLowerInvariant(propertyName[0]);
        return SymbolFormatting.EscapeIdentifier(first + propertyName.Substring(1));
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeXml(string value)
    {
        return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
