using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Forge.Generators.Shared;

internal static class DeltaEmitter
{
    private const string DeltaComparerAttributeName = "Forge.Delta.DeltaComparerAttribute";
    private const string DeltaIgnoreAttributeName = "Forge.Delta.DeltaIgnoreAttribute";
    private const string GenerateDeltaAttributeName = "Forge.Delta.GenerateDeltaAttribute";
    private const string GenerateSyncAttributeName = "Forge.Sync.GenerateSyncAttribute";

    public static string Emit(INamedTypeSymbol type)
    {
        return Emit(type, System.Array.Empty<IPropertySymbol>());
    }

    public static string Emit(
        INamedTypeSymbol type,
        IReadOnlyCollection<IPropertySymbol> excludedProperties)
    {
        return Emit(
            type,
            excludedProperties,
            type.Name + "Delta",
            SymbolFormatting.Namespace(type),
            type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal");
    }

    public static string Emit(
        INamedTypeSymbol type,
        IReadOnlyCollection<IPropertySymbol> excludedProperties,
        string deltaName,
        string namespaceName,
        string accessibility)
    {
        return Emit(
            type,
            excludedProperties,
            deltaName,
            namespaceName,
            accessibility,
            new Dictionary<string, INamedTypeSymbol>(System.StringComparer.Ordinal));
    }

    public static string Emit(
        INamedTypeSymbol type,
        IReadOnlyCollection<IPropertySymbol> excludedProperties,
        string deltaName,
        string namespaceName,
        string accessibility,
        IReadOnlyDictionary<string, INamedTypeSymbol> comparerOverrides)
    {
        var excludedNames = new HashSet<string>(
            excludedProperties.Select(static property => property.Name),
            System.StringComparer.Ordinal);
        var properties = GetProperties(type)
            .Where(property => !excludedNames.Contains(property.Name))
            .Select(property => CreatePropertyModel(property, comparerOverrides))
            .ToArray();
        var typeName = SymbolFormatting.TypeName(type);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.AppendLine("/// <summary>");
        builder.Append("/// Generated change description for <see cref=\"")
            .Append(typeName)
            .AppendLine("\"/>.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("[global::System.Diagnostics.DebuggerDisplay(\"Changes = {Changes.Count}\")]");
        builder.Append(accessibility).Append(" sealed class ").Append(deltaName)
            .AppendLine(" : global::Forge.Delta.IDelta");
        builder.AppendLine("{");

        EmitComparerFields(builder, properties);
        EmitConstructor(builder, deltaName, properties);
        builder.AppendLine();
        EmitProperties(builder, properties);
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets changed properties in deterministic declaration order.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::Forge.Delta.PropertyChange> Changes { get; }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets a value indicating whether any generated state changed.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public bool HasChanges => Changes.Count != 0;");
        builder.AppendLine();
        EmitAreEquivalent(builder, type, typeName, properties);
        builder.AppendLine();
        EmitSemanticHash(builder, type, typeName, properties);
        builder.AppendLine();
        EmitBetween(builder, type, typeName, deltaName, properties);
        builder.AppendLine();
        EmitMergeAnalysis(builder, type, typeName, deltaName, properties);
        builder.AppendLine();
        EmitInvert(builder, deltaName, properties);
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitComparerFields(StringBuilder builder, IReadOnlyList<PropertyModel> properties)
    {
        var emittedAny = false;
        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            var comparerType = property.ComparerType;
            if (comparerType is null)
            {
                continue;
            }

            builder.Append("    private static readonly global::System.Collections.Generic.IEqualityComparer<")
                .Append(SymbolFormatting.TypeName(property.Property.Type))
                .Append("> s_property")
                .Append(index)
                .Append("Comparer = new ")
                .Append(SymbolFormatting.TypeName(comparerType))
                .AppendLine("();");
            emittedAny = true;
        }

        if (emittedAny)
        {
            builder.AppendLine();
        }
    }

    private static void EmitConstructor(
        StringBuilder builder,
        string deltaName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.Append("    private ").Append(deltaName).AppendLine("(");

        var parameters = new List<string>();
        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            parameters.Add(
                "        global::Forge.Delta.ValueChange<" +
                SymbolFormatting.TypeName(property.Property.Type) +
                "> property" + index + "Change");

            var nestedDeltaType = property.NestedDeltaType;
            if (nestedDeltaType is not null)
            {
                parameters.Add(
                    "        " + NestedDeltaTypeName(nestedDeltaType) +
                    "? property" + index + "Delta");
            }
        }

        if (parameters.Count == 0)
        {
            builder.AppendLine("        )");
        }
        else
        {
            for (var index = 0; index < parameters.Count; index++)
            {
                builder.Append(parameters[index])
                    .AppendLine(index == parameters.Count - 1 ? ")" : ",");
            }
        }

        builder.AppendLine("    {");

        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
            builder.Append("        ").Append(propertyName).Append("Change = property")
                .Append(index).AppendLine("Change;");

            if (property.NestedDeltaType is not null)
            {
                builder.Append("        ").Append(propertyName).Append("Delta = property")
                    .Append(index).AppendLine("Delta;");
            }
        }

        if (properties.Count != 0)
        {
            builder.AppendLine();
        }

        builder.AppendLine(
            "        global::System.Collections.Generic.List<global::Forge.Delta.PropertyChange>? changes = null;");

        for (var index = 0; index < properties.Count; index++)
        {
            EmitChangeCollection(builder, properties[index], index);
        }

        builder.AppendLine();
        builder.AppendLine(
            "        Changes = changes is null ? global::System.Array.Empty<global::Forge.Delta.PropertyChange>() : changes.AsReadOnly();");
        builder.AppendLine("    }");
    }

    private static void EmitChangeCollection(StringBuilder builder, PropertyModel property, int index)
    {
        var path = EscapeString(property.Property.Name);
        builder.Append("        if (property").Append(index).AppendLine("Change.HasChanged)");
        builder.AppendLine("        {");

        var nestedDeltaType = property.NestedDeltaType;
        if (nestedDeltaType is null)
        {
            EmitDirectChange(builder, path, index, "            ");
        }
        else
        {
            builder.Append("            if (property").Append(index).AppendLine("Delta is { HasChanges: true } nestedDelta)");
            builder.AppendLine("            {");
            builder.AppendLine("                foreach (var nestedChange in nestedDelta.Changes)");
            builder.AppendLine("                {");
            builder.Append("                    (changes ??= new global::System.Collections.Generic.List<")
                .Append("global::Forge.Delta.PropertyChange>()).Add(")
                .Append("new global::Forge.Delta.PropertyChange(\"")
                .Append(path)
                .Append(".\" + nestedChange.Path, nestedChange.Before, nestedChange.After));")
                .AppendLine();
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine("            else");
            builder.AppendLine("            {");
            EmitDirectChange(builder, path, index, "                ");
            builder.AppendLine("            }");
        }

        builder.AppendLine("        }");
    }

    private static void EmitDirectChange(StringBuilder builder, string path, int index, string indent)
    {
        builder.Append(indent)
            .Append("(changes ??= new global::System.Collections.Generic.List<global::Forge.Delta.PropertyChange>()).Add(new global::Forge.Delta.PropertyChange(\"")
            .Append(path)
            .Append("\", property")
            .Append(index)
            .Append("Change.Before, property")
            .Append(index)
            .AppendLine("Change.After));");
    }

    private static void EmitProperties(StringBuilder builder, IReadOnlyList<PropertyModel> properties)
    {
        foreach (var property in properties)
        {
            var propertyType = SymbolFormatting.TypeName(property.Property.Type);
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
            builder.AppendLine("    /// <summary>");
            builder.Append("    /// Gets the typed change for ").Append(property.Property.Name).AppendLine(".");
            builder.AppendLine("    /// </summary>");
            builder.Append("    public global::Forge.Delta.ValueChange<")
                .Append(propertyType)
                .Append("> ")
                .Append(propertyName)
                .AppendLine("Change { get; }");
            builder.AppendLine();

            var nestedDeltaType = property.NestedDeltaType;
            if (nestedDeltaType is not null)
            {
                builder.AppendLine("    /// <summary>");
                builder.Append("    /// Gets the nested generated delta for ").Append(property.Property.Name).AppendLine(" when both values exist.");
                builder.AppendLine("    /// </summary>");
                builder.Append("    public ")
                    .Append(NestedDeltaTypeName(nestedDeltaType))
                    .Append("? ")
                    .Append(propertyName)
                    .AppendLine("Delta { get; }");
                builder.AppendLine();
            }
        }
    }

    private static void EmitAreEquivalent(
        StringBuilder builder,
        INamedTypeSymbol type,
        string typeName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Determines whether two values are equivalent under generated Delta semantics without creating a detailed Delta.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static bool AreEquivalent(")
            .Append(typeName).Append(" before, ").Append(typeName).AppendLine(" after)");
        builder.AppendLine("    {");

        if (type.IsReferenceType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(before);");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(after);");
            builder.AppendLine();
        }

        for (var index = 0; index < properties.Count; index++)
        {
            EmitEquivalenceComparison(builder, properties[index], index);
        }

        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
    }

    private static void EmitEquivalenceComparison(
        StringBuilder builder,
        PropertyModel property,
        int index)
    {
        var propertyType = SymbolFormatting.TypeName(property.Property.Type);
        var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
        if (property.ComparerType is not null)
        {
            builder.Append("        if (!s_property").Append(index).Append("Comparer.Equals(before.")
                .Append(propertyName).Append(", after.").Append(propertyName).AppendLine("))");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine();
            return;
        }

        var nestedDeltaType = property.NestedDeltaType;
        if (nestedDeltaType is null)
        {
            builder.Append("        if (!global::System.Collections.Generic.EqualityComparer<")
                .Append(propertyType).Append(">.Default.Equals(before.").Append(propertyName)
                .Append(", after.").Append(propertyName).AppendLine("))");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine();
            return;
        }

        var nestedDeltaTypeName = NestedDeltaTypeName(nestedDeltaType);
        var nestedSyncTypeName = property.NestedUsesSync ? NestedSyncTypeName(nestedDeltaType) : null;
        if (IsNullableValueType(property.Property.Type))
        {
            builder.Append("        var property").Append(index).Append("Before = before.")
                .Append(propertyName).AppendLine(";");
            builder.Append("        var property").Append(index).Append("After = after.")
                .Append(propertyName).AppendLine(";");
            builder.Append("        if (property").Append(index).Append("Before.HasValue != property")
                .Append(index).AppendLine("After.HasValue)");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.Append("        if (property").Append(index).AppendLine("Before.HasValue)");
            builder.AppendLine("        {");
            if (nestedSyncTypeName is not null)
            {
                builder.Append("            if (").Append(nestedSyncTypeName).Append(".GetKey(property")
                    .Append(index).Append("Before.Value) != ").Append(nestedSyncTypeName)
                    .Append(".GetKey(property").Append(index).AppendLine("After.Value))");
                builder.AppendLine("            {");
                builder.AppendLine("                return false;");
                builder.AppendLine("            }");
            }

            builder.Append("            if (!").Append(nestedDeltaTypeName).Append(".AreEquivalent(property")
                .Append(index).Append("Before.Value, property").Append(index).AppendLine("After.Value))");
            builder.AppendLine("            {");
            builder.AppendLine("                return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            return;
        }

        if (property.Property.Type.IsReferenceType)
        {
            builder.Append("        var property").Append(index).Append("Before = before.")
                .Append(propertyName).AppendLine(";");
            builder.Append("        var property").Append(index).Append("After = after.")
                .Append(propertyName).AppendLine(";");
            builder.Append("        if (property").Append(index).Append("Before is null || property")
                .Append(index).AppendLine("After is null)");
            builder.AppendLine("        {");
            builder.Append("            if (!global::System.Object.ReferenceEquals(property").Append(index)
                .Append("Before, property").Append(index).AppendLine("After))");
            builder.AppendLine("            {");
            builder.AppendLine("                return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            if (nestedSyncTypeName is not null)
            {
                builder.Append("            if (").Append(nestedSyncTypeName).Append(".GetKey(property")
                    .Append(index).Append("Before) != ").Append(nestedSyncTypeName)
                    .Append(".GetKey(property").Append(index).AppendLine("After))");
                builder.AppendLine("            {");
                builder.AppendLine("                return false;");
                builder.AppendLine("            }");
            }

            builder.Append("            if (!").Append(nestedDeltaTypeName).Append(".AreEquivalent(property")
                .Append(index).Append("Before, property").Append(index).AppendLine("After))");
            builder.AppendLine("            {");
            builder.AppendLine("                return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            return;
        }

        if (nestedSyncTypeName is not null)
        {
            builder.Append("        if (").Append(nestedSyncTypeName).Append(".GetKey(before.")
                .Append(propertyName).Append(") != ").Append(nestedSyncTypeName)
                .Append(".GetKey(after.").Append(propertyName).AppendLine("))");
            builder.AppendLine("        {");
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
        }

        builder.Append("        if (!").Append(nestedDeltaTypeName).Append(".AreEquivalent(before.")
            .Append(propertyName).Append(", after.").Append(propertyName).AppendLine("))");
        builder.AppendLine("        {");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void EmitInvert(
        StringBuilder builder,
        string deltaName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Creates the exact reverse description of this generated Delta.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public ").Append(deltaName).AppendLine(" Invert()");
        builder.AppendLine("    {");
        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            var propertyType = SymbolFormatting.TypeName(property.Property.Type);
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
            builder.Append("        var property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType).Append(">.FromComparison(").Append(propertyName).Append("Change.After, ")
                .Append(propertyName).Append("Change.Before, ").Append(propertyName).AppendLine("Change.HasChanged);");
            if (property.NestedDeltaType is not null)
            {
                builder.Append("        var property").Append(index).Append("Delta = ").Append(propertyName)
                    .AppendLine("Delta?.Invert();");
            }
        }

        if (properties.Count != 0)
        {
            builder.AppendLine();
        }

        builder.Append("        return new ").Append(deltaName).AppendLine("(");
        var arguments = new List<string>();
        for (var index = 0; index < properties.Count; index++)
        {
            arguments.Add("            property" + index + "Change");
            if (properties[index].NestedDeltaType is not null)
            {
                arguments.Add("            property" + index + "Delta");
            }
        }

        if (arguments.Count == 0)
        {
            builder.AppendLine("        );");
        }
        else
        {
            for (var index = 0; index < arguments.Count; index++)
            {
                builder.Append(arguments[index]).AppendLine(index == arguments.Count - 1 ? ");" : ",");
            }
        }

        builder.AppendLine("    }");
    }

    private static void EmitMergeAnalysis(
        StringBuilder builder,
        INamedTypeSymbol type,
        string typeName,
        string deltaName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Analyzes baseline, current and desired state for semantic same-property conflicts.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static global::Forge.Delta.MergeAnalysis<").Append(deltaName).Append("> AnalyzeMerge(")
            .Append(typeName).Append(" baseline, ").Append(typeName).Append(" current, ").Append(typeName).AppendLine(" desired)");
        builder.AppendLine("    {");
        if (type.IsReferenceType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(baseline);");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(current);");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(desired);");
            builder.AppendLine();
        }

        builder.Append("        var currentDelta = ").Append(deltaName).AppendLine(".Between(baseline, current);");
        builder.Append("        var desiredDelta = ").Append(deltaName).AppendLine(".Between(baseline, desired);");
        builder.AppendLine("        global::System.Collections.Generic.List<global::Forge.Delta.MergeConflict>? conflicts = null;");
        builder.AppendLine();

        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
            var path = EscapeString(property.Property.Name);
            var baselineValue = "baseline." + propertyName;
            var currentValue = "current." + propertyName;
            var desiredValue = "desired." + propertyName;
            builder.Append("        var property").Append(index).Append("CurrentChanged = !(")
                .Append(EquivalentExpression(property, baselineValue, currentValue, index)).AppendLine(");");
            builder.Append("        var property").Append(index).Append("DesiredChanged = !(")
                .Append(EquivalentExpression(property, baselineValue, desiredValue, index)).AppendLine(");");
            builder.Append("        if (property").Append(index).Append("CurrentChanged && property").Append(index)
                .Append("DesiredChanged && !(").Append(EquivalentExpression(property, currentValue, desiredValue, index)).AppendLine("))");
            builder.AppendLine("        {");
            builder.Append("            (conflicts ??= new global::System.Collections.Generic.List<global::Forge.Delta.MergeConflict>()).Add(")
                .Append("new global::Forge.Delta.MergeConflict(\"").Append(path).Append("\", ")
                .Append(baselineValue).Append(", ").Append(currentValue).Append(", ").Append(desiredValue).AppendLine("));");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.Append("        return new global::Forge.Delta.MergeAnalysis<").Append(deltaName)
            .AppendLine(">(currentDelta, desiredDelta, conflicts ?? global::System.Array.Empty<global::Forge.Delta.MergeConflict>());");
        builder.AppendLine("    }");
    }

    private static string EquivalentExpression(PropertyModel property, string left, string right, int index)
    {
        if (property.ComparerType is not null)
        {
            return "s_property" + index + "Comparer.Equals(" + left + ", " + right + ")";
        }

        var propertyType = SymbolFormatting.TypeName(property.Property.Type);
        var nestedDeltaType = property.NestedDeltaType;
        if (nestedDeltaType is null)
        {
            return "global::System.Collections.Generic.EqualityComparer<" + propertyType + ">.Default.Equals(" + left + ", " + right + ")";
        }

        var nestedDeltaTypeName = NestedDeltaTypeName(nestedDeltaType);
        var nestedSyncTypeName = property.NestedUsesSync ? NestedSyncTypeName(nestedDeltaType) : null;
        var keyCheck = nestedSyncTypeName is null
            ? string.Empty
            : nestedSyncTypeName + ".GetKey({0}) == " + nestedSyncTypeName + ".GetKey({1}) && ";

        if (IsNullableValueType(property.Property.Type))
        {
            var key = string.IsNullOrEmpty(keyCheck)
                ? string.Empty
                : string.Format(System.Globalization.CultureInfo.InvariantCulture, keyCheck, left + ".Value", right + ".Value");
            return "((!" + left + ".HasValue && !" + right + ".HasValue) || (" + left + ".HasValue && " + right +
                ".HasValue && " + key + nestedDeltaTypeName + ".AreEquivalent(" + left + ".Value, " + right + ".Value)))";
        }

        if (property.Property.Type.IsReferenceType)
        {
            var key = string.IsNullOrEmpty(keyCheck)
                ? string.Empty
                : string.Format(System.Globalization.CultureInfo.InvariantCulture, keyCheck, left, right);
            return "(global::System.Object.ReferenceEquals(" + left + ", " + right + ") || (" + left + " is not null && " + right +
                " is not null && " + key + nestedDeltaTypeName + ".AreEquivalent(" + left + ", " + right + ")))";
        }

        var valueKey = string.IsNullOrEmpty(keyCheck)
            ? string.Empty
            : string.Format(System.Globalization.CultureInfo.InvariantCulture, keyCheck, left, right);
        return "(" + valueKey + nestedDeltaTypeName + ".AreEquivalent(" + left + ", " + right + "))";
    }

    private static void EmitSemanticHash(
        StringBuilder builder,
        INamedTypeSymbol type,
        string typeName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets an in-process semantic hash code consistent with generated Delta equality semantics.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static int GetSemanticHashCode(").Append(typeName).AppendLine(" value)");
        builder.AppendLine("    {");
        if (type.IsReferenceType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(value);");
        }

        builder.AppendLine("        var hash = new global::System.HashCode();");
        for (var index = 0; index < properties.Count; index++)
        {
            var property = properties[index];
            var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
            var propertyType = SymbolFormatting.TypeName(property.Property.Type);
            if (property.ComparerType is not null)
            {
                builder.Append("        hash.Add(value.").Append(propertyName).Append(", s_property")
                    .Append(index).AppendLine("Comparer);");
                continue;
            }

            if (property.NestedDeltaType is null)
            {
                builder.Append("        hash.Add(value.").Append(propertyName)
                    .Append(", global::System.Collections.Generic.EqualityComparer<").Append(propertyType)
                    .AppendLine(">.Default);");
                continue;
            }

            var nestedDelta = NestedDeltaTypeName(property.NestedDeltaType);
            var nestedSync = property.NestedUsesSync ? NestedSyncTypeName(property.NestedDeltaType) : null;
            if (IsNullableValueType(property.Property.Type))
            {
                builder.Append("        if (value.").Append(propertyName).AppendLine(".HasValue)");
                builder.AppendLine("        {");
                if (nestedSync is not null)
                {
                    builder.Append("            hash.Add(").Append(nestedSync).Append(".GetKey(value.")
                        .Append(propertyName).AppendLine(".Value));");
                }
                builder.Append("            hash.Add(").Append(nestedDelta).Append(".GetSemanticHashCode(value.")
                    .Append(propertyName).AppendLine(".Value));");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            hash.Add(0);");
                builder.AppendLine("        }");
                continue;
            }

            if (property.Property.Type.IsReferenceType)
            {
                builder.Append("        if (value.").Append(propertyName).AppendLine(" is null)");
                builder.AppendLine("        {");
                builder.AppendLine("            hash.Add(0);");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                if (nestedSync is not null)
                {
                    builder.Append("            hash.Add(").Append(nestedSync).Append(".GetKey(value.")
                        .Append(propertyName).AppendLine("));");
                }
                builder.Append("            hash.Add(").Append(nestedDelta).Append(".GetSemanticHashCode(value.")
                    .Append(propertyName).AppendLine("));");
                builder.AppendLine("        }");
                continue;
            }

            if (nestedSync is not null)
            {
                builder.Append("        hash.Add(").Append(nestedSync).Append(".GetKey(value.")
                    .Append(propertyName).AppendLine("));");
            }
            builder.Append("        hash.Add(").Append(nestedDelta).Append(".GetSemanticHashCode(value.")
                .Append(propertyName).AppendLine("));");
        }

        builder.AppendLine("        return hash.ToHashCode();");
        builder.AppendLine("    }");
    }

    private static void EmitBetween(
        StringBuilder builder,
        INamedTypeSymbol type,
        string typeName,
        string deltaName,
        IReadOnlyList<PropertyModel> properties)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Creates a strongly typed Delta between two states.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    public static ").Append(deltaName).Append(" Between(")
            .Append(typeName).Append(" before, ").Append(typeName).AppendLine(" after)");
        builder.AppendLine("    {");

        if (type.IsReferenceType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(before);");
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(after);");
            builder.AppendLine();
        }

        for (var index = 0; index < properties.Count; index++)
        {
            EmitPropertyComparison(builder, properties[index], index);
            builder.AppendLine();
        }

        builder.Append("        return new ").Append(deltaName).AppendLine("(");
        var arguments = new List<string>();
        for (var index = 0; index < properties.Count; index++)
        {
            arguments.Add("            property" + index + "Change");
            if (properties[index].NestedDeltaType is not null)
            {
                arguments.Add("            property" + index + "Delta");
            }
        }

        if (arguments.Count == 0)
        {
            builder.AppendLine("        );");
        }
        else
        {
            for (var index = 0; index < arguments.Count; index++)
            {
                builder.Append(arguments[index])
                    .AppendLine(index == arguments.Count - 1 ? ");" : ",");
            }
        }

        builder.AppendLine("    }");
    }

    private static void EmitPropertyComparison(StringBuilder builder, PropertyModel property, int index)
    {
        var propertyType = SymbolFormatting.TypeName(property.Property.Type);
        var propertyName = SymbolFormatting.EscapeIdentifier(property.Property.Name);
        var comparerType = property.ComparerType;

        if (comparerType is not null)
        {
            builder.Append("        var property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType)
                .Append(">.Create(before.")
                .Append(propertyName)
                .Append(", after.")
                .Append(propertyName)
                .Append(", ")
                .Append("s_property")
                .Append(index)
                .AppendLine("Comparer);");
            return;
        }

        var nestedDeltaType = property.NestedDeltaType;
        if (nestedDeltaType is null)
        {
            builder.Append("        var property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType)
                .Append(">.Create(before.")
                .Append(propertyName)
                .Append(", after.")
                .Append(propertyName)
                .AppendLine(");");
            return;
        }

        var nestedDeltaTypeName = NestedDeltaTypeName(nestedDeltaType);
        var nestedSyncTypeName = property.NestedUsesSync ? NestedSyncTypeName(nestedDeltaType) : null;
        builder.Append("        var property").Append(index).Append("Before = before.")
            .Append(propertyName).AppendLine(";");
        builder.Append("        var property").Append(index).Append("After = after.")
            .Append(propertyName).AppendLine(";");
        builder.Append("        ").Append(nestedDeltaTypeName).Append("? property")
            .Append(index).AppendLine("Delta = null;");
        builder.Append("        global::Forge.Delta.ValueChange<").Append(propertyType).Append("> property")
            .Append(index).AppendLine("Change;");

        if (IsNullableValueType(property.Property.Type))
        {
            builder.Append("        if (property").Append(index).Append("Before.HasValue && property")
                .Append(index).AppendLine("After.HasValue)");
            builder.AppendLine("        {");
            builder.Append("            property").Append(index).Append("Delta = ")
                .Append(nestedDeltaTypeName).Append(".Between(property").Append(index)
                .Append("Before.Value, property").Append(index).AppendLine("After.Value);");
            builder.Append("            property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType).Append(">.FromComparison(property").Append(index)
                .Append("Before, property").Append(index).Append("After, ");
            EmitNestedChangedExpression(
                builder,
                nestedSyncTypeName,
                "property" + index + "Before.Value",
                "property" + index + "After.Value",
                "property" + index + "Delta.HasChanges");
            builder.AppendLine(");");
            builder.AppendLine("        }");
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType).Append(">.Create(property").Append(index)
                .Append("Before, property").Append(index).AppendLine("After);");
            builder.AppendLine("        }");
            return;
        }

        if (property.Property.Type.IsReferenceType)
        {
            builder.Append("        if (property").Append(index).Append("Before is not null && property")
                .Append(index).AppendLine("After is not null)");
            builder.AppendLine("        {");
            builder.Append("            property").Append(index).Append("Delta = ")
                .Append(nestedDeltaTypeName).Append(".Between(property").Append(index)
                .Append("Before, property").Append(index).AppendLine("After);");
            builder.Append("            property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType).Append(">.FromComparison(property").Append(index)
                .Append("Before, property").Append(index).Append("After, ");
            EmitNestedChangedExpression(
                builder,
                nestedSyncTypeName,
                "property" + index + "Before",
                "property" + index + "After",
                "property" + index + "Delta.HasChanges");
            builder.AppendLine(");");
            builder.AppendLine("        }");
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
                .Append(propertyType).Append(">.Create(property").Append(index)
                .Append("Before, property").Append(index).AppendLine("After);");
            builder.AppendLine("        }");
            return;
        }

        builder.Append("        property").Append(index).Append("Delta = ")
            .Append(nestedDeltaTypeName).Append(".Between(property").Append(index)
            .Append("Before, property").Append(index).AppendLine("After);");
        builder.Append("        property").Append(index).Append("Change = global::Forge.Delta.ValueChange<")
            .Append(propertyType).Append(">.FromComparison(property").Append(index)
            .Append("Before, property").Append(index).Append("After, ");
        EmitNestedChangedExpression(
            builder,
            nestedSyncTypeName,
            "property" + index + "Before",
            "property" + index + "After",
            "property" + index + "Delta.HasChanges");
        builder.AppendLine(");");
    }

    private static void EmitNestedChangedExpression(
        StringBuilder builder,
        string? nestedSyncTypeName,
        string beforeExpression,
        string afterExpression,
        string deltaHasChangesExpression)
    {
        if (nestedSyncTypeName is not null)
        {
            builder.Append(nestedSyncTypeName).Append(".GetKey(").Append(beforeExpression)
                .Append(") != ").Append(nestedSyncTypeName).Append(".GetKey(")
                .Append(afterExpression).Append(") || ");
        }

        builder.Append(deltaHasChangesExpression);
    }

    internal static IReadOnlyList<IPropertySymbol> GetProperties(INamedTypeSymbol type)
    {
        return GetAllProperties(type)
            .Where(static property => !IsIgnored(property))
            .ToArray();
    }

    internal static IReadOnlyList<IPropertySymbol> GetAllProperties(INamedTypeSymbol type)
    {
        var hierarchy = new Stack<INamedTypeSymbol>();
        for (INamedTypeSymbol? current = type; current is not null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            hierarchy.Push(current);
        }

        var properties = new List<IPropertySymbol>();
        var indexes = new Dictionary<string, int>(System.StringComparer.Ordinal);

        while (hierarchy.Count != 0)
        {
            var current = hierarchy.Pop();
            var declaredProperties = current.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property =>
                    !property.IsStatic
                    && !property.IsIndexer
                    && property.DeclaredAccessibility == Accessibility.Public
                    && property.GetMethod is not null)
                .OrderBy(static property => property.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
                .ThenBy(static property => property.Name, System.StringComparer.Ordinal);

            foreach (var property in declaredProperties)
            {
                if (indexes.TryGetValue(property.Name, out var existingIndex))
                {
                    properties[existingIndex] = property;
                }
                else
                {
                    indexes.Add(property.Name, properties.Count);
                    properties.Add(property);
                }
            }
        }

        return properties;
    }

    internal static bool IsIgnored(IPropertySymbol property)
    {
        return HasAttribute(property, DeltaIgnoreAttributeName);
    }

    private static PropertyModel CreatePropertyModel(
        IPropertySymbol property,
        IReadOnlyDictionary<string, INamedTypeSymbol>? comparerOverrides = null)
    {
        var comparerType = comparerOverrides is not null
            && comparerOverrides.TryGetValue(property.Name, out var comparerOverride)
                ? comparerOverride
                : GetComparerType(property);
        var nestedDeltaType = comparerType is null ? GetNestedDeltaType(property.Type) : null;
        return new PropertyModel(
            property,
            comparerType,
            nestedDeltaType,
            nestedDeltaType is not null && HasAttribute(nestedDeltaType, GenerateSyncAttributeName));
    }

    internal static INamedTypeSymbol? GetComparerType(IPropertySymbol property)
    {
        var attribute = FindAttribute(property, DeltaComparerAttributeName);
        if (attribute is null || attribute.ConstructorArguments.Length == 0)
        {
            return null;
        }

        return attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
    }

    private static INamedTypeSymbol? GetNestedDeltaType(ITypeSymbol propertyType)
    {
        var candidate = UnwrapNullable(propertyType);
        if (candidate is null || candidate.Arity != 0 || candidate.ContainingType is not null)
        {
            return null;
        }

        return HasAttribute(candidate, GenerateDeltaAttributeName)
               || HasAttribute(candidate, GenerateSyncAttributeName)
            ? candidate
            : null;
    }

    private static INamedTypeSymbol? UnwrapNullable(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return null;
        }

        if (namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0] as INamedTypeSymbol;
        }

        return namedType;
    }

    private static bool IsNullableValueType(ITypeSymbol type)
    {
        return type is INamedTypeSymbol namedType
               && namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
    }

    private static bool HasAttribute(ISymbol symbol, string metadataName)
    {
        return FindAttribute(symbol, metadataName) is not null;
    }

    private static AttributeData? FindAttribute(ISymbol symbol, string metadataName)
    {
        for (ISymbol? current = symbol; current is not null; current = GetOverriddenSymbol(current))
        {
            var attribute = current.GetAttributes().FirstOrDefault(candidate =>
                string.Equals(
                    candidate.AttributeClass?.ToDisplayString(),
                    metadataName,
                    System.StringComparison.Ordinal));

            if (attribute is not null)
            {
                return attribute;
            }
        }

        return null;
    }

    private static ISymbol? GetOverriddenSymbol(ISymbol symbol)
    {
        return symbol is IPropertySymbol property ? property.OverriddenProperty : null;
    }

    private static string NestedDeltaTypeName(INamedTypeSymbol type)
    {
        var namespaceName = SymbolFormatting.Namespace(type);
        return string.IsNullOrEmpty(namespaceName)
            ? "global::" + type.Name + "Delta"
            : "global::" + namespaceName + "." + type.Name + "Delta";
    }

    private static string NestedSyncTypeName(INamedTypeSymbol type)
    {
        var namespaceName = SymbolFormatting.Namespace(type);
        return string.IsNullOrEmpty(namespaceName)
            ? "global::" + type.Name + "Sync"
            : "global::" + namespaceName + "." + type.Name + "Sync";
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed class PropertyModel
    {
        public PropertyModel(
            IPropertySymbol property,
            INamedTypeSymbol? comparerType,
            INamedTypeSymbol? nestedDeltaType,
            bool nestedUsesSync)
        {
            Property = property;
            ComparerType = comparerType;
            NestedDeltaType = nestedDeltaType;
            NestedUsesSync = nestedUsesSync;
        }

        public IPropertySymbol Property { get; }

        public INamedTypeSymbol? ComparerType { get; }

        public INamedTypeSymbol? NestedDeltaType { get; }

        public bool NestedUsesSync { get; }
    }
}
